name: CI/CD IaC

on:
  push:
    branches: [ main ]
    paths:
      - "src/DevOpsMetrics.Infrastructure/**"
      - ".github/workflows/iac.yml"
  workflow_dispatch:

jobs:
  validate_deploy:
    runs-on: ubuntu-latest
    
    steps:

    - name: "Check mandatory Secrets"
      env: 
        resource_suffix_secret: ${{ secrets.AZ_RESOURCES_SUFFIX }}
        location_secret: ${{ secrets.LOCATION }}

      if: ${{ (env.resource_suffix_secret == '') || (env.location_secret == '') }}
      run: throw "All Secrects must be set"
        
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZ_CLIENT_ID }}","clientSecret":"${{ secrets.AZ_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZ_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZ_TENANT_ID }}"}'

    - name: Run bicep lint
      working-directory: src/DevOpsMetrics.Infrastructure/Templates/
      run: az bicep build --file Main.bicep
  
    - name: Run bicep validation
      working-directory: src/DevOpsMetrics.Infrastructure/Templates/
      run: az deployment sub validate --template-file Main.bicep --location "${{ secrets.LOCATION }}" --parameters resourcesSuffix="${{ secrets.AZ_RESOURCES_SUFFIX }}" "azureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "gitHubClientId=${{ secrets.GitHubClientId }}" "gitHubClientSecret=${{ secrets.GitHubClientSecret }}"

    - name: Run bicep preview
      working-directory: src/DevOpsMetrics.Infrastructure/Templates/
      run: az deployment sub what-if --template-file Main.bicep --location "${{ secrets.LOCATION }}" --parameters resourcesSuffix="${{ secrets.AZ_RESOURCES_SUFFIX }}" "azureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "gitHubClientId=${{ secrets.GitHubClientId }}" "gitHubClientSecret=${{ secrets.GitHubClientSecret }}"

    - name: Deploy bicep
      working-directory: src/DevOpsMetrics.Infrastructure/Templates/
      run: az deployment sub create --template-file Main.bicep --location "${{ secrets.LOCATION }}" --parameters resourcesSuffix="${{ secrets.AZ_RESOURCES_SUFFIX }}" "azureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "gitHubClientId=${{ secrets.GitHubClientId }}" "gitHubClientSecret=${{ secrets.GitHubClientSecret }}"